<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\external\orcahello\ModeratorFrontEnd\AIForOrcas\AIForOrcas.Client.BL\AIForOrcas.Client.BL.csproj" />
    <ProjectReference Include="..\external\orcahello\ModeratorFrontEnd\AIForOrcas\AIForOrcas.DTO\AIForOrcas.DTO.csproj" />
  </ItemGroup>

</Project>
