# Copyright (c) PODS-AI contributors
# SPDX-License-Identifier: MIT
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: Validate-YAML

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate-yaml:
    permissions:
      actions: write  # for fkirc/skip-duplicate-actions to skip or stop workflow runs
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578  # v5.3.2
        with:
          cancel_others: 'false'
          paths: '["**.yml", "**.yaml"]'

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        if: steps.skip_check.outputs.should_skip != 'true'

      - name: Install yamllint
        if: steps.skip_check.outputs.should_skip != 'true'
        run: pip install yamllint

      - name: Validate YAML
        if: steps.skip_check.outputs.should_skip != 'true'
        run: yamllint .
